---
- name: Create kerberos realm
  hosts: kerberos_servers[0]
  become: yes
  vars:
    kerberos_keytabs:
      - admin/admin
      - afs/{{ openafs_cell }}
  roles:
  - kerberos_server

- name: Install OpenAFS servers
  hosts:
    - openafs_databases
    - openafs_fileservers
  become: yes
  roles:
    - openafs_server

- name: Install OpenAFS clients
  hosts: openafs_clients
  become: yes
  roles:
    - kerberos_client
    - openafs_client

- name: Create cell volumes
  hosts: openafs_clients[0]
  roles:
    - openafs_cell
