---
- name: Create Kerberos realm
  hosts: kdc[0]
  become: yes
  roles:
    - kerberos_server

- name: Install Kerberos clients
  hosts: all
  become: yes
  roles:
    - kerberos_client

- name: Install OpenAFS servers
  hosts:
    - databases
    - fileservers
  become: yes
  roles:
    - openafs_server

- name: Install OpenAFS clients
  hosts: clients
  become: yes
  roles:
    - openafs_client

- name: Create cell volumes
  hosts: clients[0]
  become: no
  roles:
    - openafs_cell
