---
- name: kerberos realm
  hosts: kerberos_servers[0]
  become: yes
  vars:
    kerberos_realm: EXAMPLE.COM
    kerberos_keytabs:
    - admin/admin
    - afs/example.com
    - tycobb
  roles:
  - kerberos_server

- name: openafs servers
  hosts:
    - openafs_databases
    - openafs_fileservers
  become: yes
  vars:
    openafs_cell: example.com
  roles:
  - openafs_server

- name: openafs cell clients
  hosts: openafs_clients
  become: yes
  roles:
  - kerberos_client
  - openafs_client
  tags: client

## mount root.cell volume
## set acls
## create and mount top-level volumes
