---
- name: Create kerberos realm
  hosts: kerberos_servers[0]
  become: yes
  vars:
    kerberos_keytabs:
      - admin/admin
      - afs/{{ openafs_cell }}
  roles:
  - kerberos_server

- name: Install OpenAFS servers
  hosts:
    - openafs_databases
    - openafs_fileservers
  become: yes
  roles:
    - openafs_server

- name: Create cell root volumes.
  hosts: openafs_clients[0]
  roles:
    - role: kerberos_client
      become: yes
    - role: openafs_client
      become: yes
  tasks:
    - import_tasks: roles/openafs_client/tasks/root-volumes.yaml

- name: Install OpenAFS clients
  hosts: openafs_clients
  become: yes
  roles:
    - kerberos_client
    - openafs_client
