---
- name: kerberos realm
  hosts: kerberos-servers[0]
  become: yes
  roles:
  - role: kerberos-server

#- name: openafs cell databases
#  hosts: openafs-databases
#  become: yes
#  roles:
#  - role: openafs-database
#
#- name: openafs cell fileservers
#  hosts: openafs-fileservers
#  become: yes
#  roles:
#  - role: openafs-fileserver
#
## create root.afs and root.cell volumes on fileserver[0] ?
#
#- name: openafs cell clients
#  hosts: openafs-clients
#  become: yes
#  roles:
#  - role: kerberos-client
#  - role: openafs-client
#
## mount root.cell volume
## set acls
## create and mount top-level volumes
#
