---
- name: kerberos realm
  hosts: kerberos-servers[0]
  become: yes
  vars:
    kerberos_realm: EXAMPLE.COM
    kerberos_principals:
    - name: admin/admin
      keytab: admin.keytab
    - name: afs/example.com
      keytab: afs.keytab
      enctype: aes256-cts-hmac-sha1-96:normal
    - name: tycobb
      keytab: tycobb.keytab
  roles:
  - kerberos-client
  - kerberos-server

- name: openafs cell databases
  hosts: openafs-databases
  become: yes
  vars:
    openafs_cell: example.com
  roles:
  - kerberos-client
  - openafs-server

#- name: openafs cell fileservers
#  hosts: openafs-fileservers
#  become: yes
#  roles:
#  - role: openafs-fileserver
#
## create root.afs and root.cell volumes on fileserver[0] ?
#
#- name: openafs cell clients
#  hosts: openafs-clients
#  become: yes
#  roles:
#  - role: kerberos-client
#  - role: openafs-client
#
## mount root.cell volume
## set acls
## create and mount top-level volumes
#
