---
- name: install kerberos server
  package:
    name: "{{ kerberos_server_package }}"
    state: present

- name: permit kerberos kdc traffic
  firewalld:
    port: 88/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: permit kerberos kadmin traffic
  firewalld:
    port: 749/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: configure kerberos kdc
  template:
    src: kdc.conf.j2
    dest: "{{ kerberos_localstatedir }}/krb5kdc/kdc.conf"
    owner: root
    group: root
    mode: 0600

- name: configure kerberos admin acls
  template:
    src: kadm5.acl.j2
    dest: "{{ kerberos_localstatedir }}/krb5kdc/kadm5.acl"
    owner: root
    group: root
    mode: 0600

- name: create kerberos kdc database
  command: >
    /sbin/kdb5_util
    -P {{ lookup('password', '/dev/null chars=ascii_letters') }}
    -r {{ kerberos_realm }}
    create -s
  args:
    creates: "{{ kerberos_localstatedir }}/krb5kdc/principal"
  register: krb5_util_results

- name: start kerberos kdc
  service:
    name: krb5kdc
    state: started

- name: start kadmin
  service:
    name: kadmin
    state: started

- name: create keytabs
  include: keytabs.yaml
  when: kerberos_principals is defined
