---
- name: install kerberos server
  package:
    name: "{{ kerberos_server_package }}"
    state: present

- name: permit kerberos kdc traffic
  firewalld:
    port: 88/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: permit kerberos kadmin traffic
  firewalld:
    port: 749/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: configure kerberos kdc
  template:
    src: kdc.conf.j2
    dest: "{{ kerberos_localstatedir }}/krb5kdc/kdc.conf"
    owner: root
    group: root
    mode: 0600

- name: configure kerberos admin acls
  template:
    src: kadm5.acl.j2
    dest: "{{ kerberos_localstatedir }}/krb5kdc/kadm5.acl"
    owner: root
    group: root
    mode: 0600

- name: create kerberos kdc database
  command: >
    /sbin/kdb5_util
    -P {{ lookup('password', '/dev/null chars=ascii_letters') }}
    -r {{ kerberos_realm }}
    create -s
  args:
    creates: "{{ kerberos_localstatedir }}/krb5kdc/principal"
  register: krb5_util_results

- name: create directory for keytabs
  file:
    path: "{{ kerberos_localstatedir }}/keytabs"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: create a kerberos admin principal
  command: >
    /sbin/kadmin.local
    -r {{ kerberos_realm }}
    -q 'add_principal -randkey {{ kerberos_admin}}@{{ kerberos_realm }}'
  register: kadmin_results
  changed_when: >
    kadmin_results.rc == 0
    and not "already exists while creating" in kadmin_results.stderr

- name: create a kerberos admin principal keytab
  command: >
    /sbin/kadmin.local
    -r {{ kerberos_realm }}
    -q 'ktadd -keytab {{ kerberos_localstatedir }}/keytabs/admin.keytab {{ kerberos_admin }}@{{ kerberos_realm }}'
  args:
    creates: "{{ kerberos_localstatedir }}/keytabs/admin.keytab"
  register: kadmin_results

- name: start kerberos kdc
  service:
    name: krb5kdc
    state: started

- name: start kadmin
  service:
    name: kadmin
    state: started
