---
# TODO: selinuxize
- name: disable selinux
  selinux:
    state: disabled
  when: ansible_distribution == "CentOS"

# TODO: firewall rules
- name: disable firewall
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  when: ansible_distribution == "CentOS"

- name: install kerberos server
  package:
    name: "{{ kerberos_server_package }}"
    state: present

- name: permit kerberos kdc traffic
  firewalld:
    port: 88/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: permit kerberos kadmin traffic
  firewalld:
    port: 749/udp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

# NOTE: /etc/krb5.conf is a prereq.
- name: configure kerberos kdc
  template:
    src: "{{ item }}.j2"
    dest: "{{ kerberos_localstatedir }}/krb5kdc/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
  - kdc.conf
  - kadm5.acl

- name: create kerberos kdc database
  command: >
    /sbin/kdb5_util
    -P {{ lookup('password', '/dev/null chars=ascii_letters') }}
    -r {{ kerberos_realm }}
    create -s
  args:
    creates: "{{ kerberos_localstatedir }}/krb5kdc/principal"
  register: krb5_util_results

- name: start kerberos kdc
  service:
    name: krb5kdc
    state: started

- name: start kadmin
  service:
    name: kadmin
    state: started

- name: create keytabs
  include: keytabs.yaml
  when: kerberos_principals is defined
