---
- name: Disable selinux
  selinux:
    state: disabled

- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit kerberos kdc traffic
  firewalld:
    port: 88/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: Permit kerberos kadmin traffic
  firewalld:
    port: 749/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: Install kerberos server
  yum:
    name: krb5-server
    state: present

- name: Set default realm
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
