---
- include: CentOS.yaml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Update cell configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ viceetcdir }}/{{ item }}"
    mode: 0644
  with_items:
    - CellServDB.local
    - ThisCell
    - cacheinfo

- name: Start OpenAFS client
  service:
    state: started
    name: openafs-client
