---
- name: disable selinux
  # TODO: enable selinux
  selinux:
    state: disabled

- name: permit afs3 traffic
  firewalld:
    port: 7000-7009/udp
    permanent: yes
    state: enabled

- name: add epel yum repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: add openafs yum repo
  yum:
    name: "{{ openafs_yum_repo }}"
    state: present
    update_cache: yes

- name: install openafs servers
  yum:
    state: present
    name:
    - openafs-server

- name: configure cell
  template:
    src: "{{ item }}.j2"
    dest: "{{ openafs_path.afsconfdir }}/{{ item }}"
    mode: 0644
  with_items:
  - CellServDB
  - ThisCell
  - UserList

- name: set service keys
  include: setkey-rxkad-krb5.yaml

- file:
    state: directory
    path: "{{ openafs_path.afslocaldir }}"
    mode: 0644
    owner: root
    group: root

- name: configure server
  template:
    src: "{{ item }}.j2"
    dest: "{{ openafs_path.afslocaldir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
  - BosConfig.new
  - NetInfo

- name: start openafs servers
  service:
    state: started
    name: openafs-server

- name: pause while starting openafs servers
  pause:
    seconds: 10
