---

#----------------------------------------
# TODO: selinux labels and firewall rules
- name: disable selinux
  selinux:
    state: disabled
- name: disable firewall
  systemd:
    name: firewalld
    enabled: no
    state: stopped
#----------------------------------------

- name: vice partitions
  include: vice-partition.yaml
  with_items: "{{ vicep.split(',') }}"
  when: vicep is defined

- name: add epel yum repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: add openafs yum repo
  yum:
    name: "{{ openafs_yum_repo }}"
    state: present
    update_cache: yes

- name: install openafs servers
  yum:
    state: present
    name:
      - openafs-server

- name: configure cell
  template:
    src: "{{ item }}.j2"
    dest: "{{ openafs_path.afsconfdir }}/{{ item }}"
    mode: 0644
  with_items:
    - CellServDB
    - ThisCell
    - UserList

- name: set service keys
  include: setkey-rxkad-krb5.yaml

- file:
    state: directory
    path: "{{ openafs_path.afslocaldir }}"
    mode: 0700
    owner: root
    group: root

- name: configure server
  template:
    src: "{{ item }}.j2"
    dest: "{{ openafs_path.afslocaldir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - BosConfig.new
    - NetInfo

- name: start openafs servers
  service:
    state: started
    name: openafs-server

- name: pause while starting openafs servers
  pause:
    seconds: 10
