---
- file:
    path: /vicep{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0700

- file:
    path: /vicep{{ item }}/AlwaysAttach
    state: touch
    owner: root
    group: root
    mode: 0700
