---
# TODO: selinux labels
- name: Disable selinux
  selinux:
    state: disabled

- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit kerberos traffic
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - 88/udp
    - 88/tcp
    - 749/udp
    - 749/tcp

- name: Install kerberos workstation
  yum:
    name: krb5-workstation
    state: present

- name: Configure kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
