---
- name: disable selinux
  selinux:
    state: disabled

- name: permit kerberos kdc traffic
  firewalld:
    port: 88/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: permit kerberos kadmin traffic
  firewalld:
    port: 749/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: install kerberos workstation
  package:
    name: "{{ kerberos_client_package }}"
    state: present

- name: configure kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
