---
- name: Create root.afs volume
  command: >
    vos create
      -server {{ groups['openafs_fileservers'][0] }}
      -partition {{ hostvars[groups['openafs_fileservers'][0]]['vicep'][0] }}
      -name root.afs
      -verbose
      -localauth
  register: vos_result
  until: >
    'communication failure' not in vos_result.stderr and
    'no quorum elected' not in vos_result.stderr
  delay: 30
  retries: 10
  ignore_errors: true
  changed_when: vos_result.rc == 0
  failed_when: >
    vos_result.rc != 0 and
    'already exists' not in vos_result.stderr
