---

# TODO:
# 1. use failed_when
# 2. stderr is not defined if vos cannot be run.
- name: Ensure root volume exists
  command: >
    vos create
      -server {{ groups['openafs_fileservers'][0] }}
      -partition {{ hostvars[groups['openafs_fileservers'][0]]['vicep'][0] }}
      -name root.afs
      -verbose
      -localauth
  register: vos_result
  until: >
    vos_result.rc == 0 or
    'Volume root.afs already exists' in vos_result.stderr
  delay: 30
  retries: 10
  ignore_errors: true
  changed_when: vos_result.rc == 0

- fail:
    msg: Unable to create root.afs volume.
  when: >
    vos_result.rc != 0
    and not 'Volume root.afs already exists' in vos_result.stderr

