---
- name: Set princ and keytab facts
  set_fact:
    princ: "afs/{{ openafs_cell }}@{{ openafs_realm }}"
    keytab: afs.{{ openafs_cell }}.keytab

- name: Install asetkey and klist
  yum:
    state: present
    name:
    - openafs-krb5
    - krb5-workstation

- name: Distribute keytab {{ keytab }}
  copy:
    src: "keytabs/{{ kdc }}/var/kerberos/keytabs/{{ keytab }}"
    dest: "{{ openafs_path.afsconfdir }}/{{ keytab }}"

- name: Scan keytab for kvnos
  shell: >
    klist -e -k {{ openafs_path.afsconfdir }}/{{ keytab }} |
    sed '1,3d' |
    sed 's/[()]//g' |
    awk '$2 == "{{ princ }}" && $3 !~ /^des/
    { printf("- kvno: %d\n  enc: %s\n", $1, $3) }'
  changed_when: False
  register: klist_result

- name: Set service keys
  command: >
    asetkey add rxkad_krb5 {{ item.kvno }} {{ kerberos_eno[item.enc] }} {{ openafs_path.afsconfdir }}/{{ keytab }} {{ princ }}
  args:
    creates: "{{ openafs_path.afsconfdir }}/KeyFileExt"
  with_items: "{{ klist_result.stdout | from_yaml }}"
