---
- name: Install asetkey
  yum:
    state: present
    name:
    - openafs-krb5

- name: Write keytab file
  command: >
    kadmin
    -r "{{ realm }}"
    -p "{{ admin_principal }}"
    -w "{{ admin_password }}"
    -q 'ktadd -norandkey -k {{ afsconfdir }}/afs.keytab afs/{{ cell }}@{{ realm }}'
  args:
    creates: "{{ afsconfdir }}/afs.keytab"

- name: Scan keytab for key numbers
  shell: >
    klist -e -k {{ afsconfdir }}/afs.keytab |
    sed '1,3d' |
    sed 's/[()]//g' |
    awk '$2 == "afs/{{ cell }}@{{ realm }}" && $3 !~ /^des/
    { printf("- kvno: %d\n  enc: %s\n", $1, $3) }'
  changed_when: False
  register: klist_result

- name: Set service key
  command: >
    asetkey add rxkad_krb5
    {{ item.kvno }}
    {{ kerberos_eno[item.enc] }}
    {{ afsconfdir }}/afs.keytab
    afs/{{ cell }}@{{ realm }}
  args:
    creates: "{{ afsconfdir }}/KeyFileExt"
  with_items: "{{ klist_result.stdout | from_yaml }}"
