---
- name: Install asetkey and klist
  yum:
    state: present
    name:
    - krb5-workstation
    - openafs-krb5

- name: Distribute keytab {{ keytab }}
  copy:
    src: "keytabs/{{ keytab_file }}"
    dest: "{{ afsconfdir }}/{{ keytab_file }}"

- name: Scan keytab for key numbers
  shell: >
    klist -e -k {{ afsconfdir }}/{{ keytab_file }} |
    sed '1,3d' |
    sed 's/[()]//g' |
    awk '$2 == "afs/{{ cell }}@{{ realm }}" && $3 !~ /^des/
    { printf("- kvno: %d\n  enc: %s\n", $1, $3) }'
  changed_when: False
  register: klist_result

- name: Set service keys
  command: >
    asetkey add rxkad_krb5
    {{ item.kvno }}
    {{ kerberos_eno[item.enc] }}
    {{ afsconfdir }}/{{ keytab_file }}
    afs/{{ cell }}@{{ realm }}
  args:
    creates: "{{ afsconfdir }}/KeyFileExt"
  with_items: "{{ klist_result.stdout | from_yaml }}"
