---
- file:
    path: /vicep{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0700

- copy:
    content: ""
    dest: /vicep{{ item }}/AlwaysAttach
    force: no
    owner: root
    group: root
    mode: 0600
