---
- name: Copy admin user keytab
  copy:
    src: "keytabs/{{ kdc }}/var/kerberos/keytabs/admin.admin.keytab"
    dest: admin.admin.keytab

- name: Get kerberos ticket
  command: "{{ kinit }} -k -t admin.admin.keytab admin/admin@{{ openafs_realm }}"

- name: Get afs token
  command: "{{ aklog }} -d -c {{ openafs_cell }}"
