---
#
# Get creds
#
# TODO: Custom become_method to get a token?
- name: Copy admin user keytab
  copy:
    src: "keytabs/{{ kdc }}/var/kerberos/keytabs/admin.admin.keytab"
    dest: admin.admin.keytab

- name: Get kerberos ticket
  command: "{{ kinit }} -k -t admin.admin.keytab admin/admin@{{ openafs_realm }}"

- name: Get afs token
  command: "{{ aklog }} -d -c {{ openafs_cell }}"

#
# Setup root.afs volume
#
- name: Create the root.afs volume
  command: "{{ vos }} create -server {{ root_server }} -partition {{ root_part }} -name root.afs -verbose"
  register: vos_result
  until: >
    'communication failure' not in vos_result.get('stderr','') and
    'no quorum elected' not in vos_result.get('stderr','') and
    'Input/output error' not in vos_result.get('stderr','')
  delay: 30
  retries: 10
  changed_when: vos_result.rc == 0
  failed_when: >
    vos_result.rc != 0 and
    'already exists' not in vos_result.get('stderr','')

- name: Grant world readable rights to /afs
  command: >
    {{ fs }} setacl
    -dir /afs/.:mount/{{ openafs_cell }}:root.afs/.
    -acl system:anyuser read

#
# Setup root.cell volume
#
- name: Create root.cell volume
  command: "{{ vos }} create -server {{ root_server }} -partition {{ root_part }} -name root.cell -verbose"
  register: vos_result
  until: >
    'communication failure' not in vos_result.get('stderr','') and
    'no quorum elected' not in vos_result.get('stderr','') and
    'Input/output error' not in vos_result.get('stderr','')
  delay: 30
  retries: 10
  changed_when: vos_result.rc == 0
  failed_when: >
    vos_result.rc != 0 and
    'already exists' not in vos_result.get('stderr','')

- name: Mount root.cell volume
  command: >
    {{ fs }} mkmount
    -dir /afs/.:mount/{{ openafs_cell }}:root.afs/{{ openafs_cell }}
    -vol root.cell
    -cell {{ openafs_cell }}
  register: fs_result
  changed_when: fs_result.rc == 0
  failed_when: >
    fs_result.rc != 0
    and 'File exists' not in fs_result.get('stderr','')

- name: Grant world readable rights to /afs/{{ openafs_cell }}
  command: >
    {{ fs }} setacl
    -dir /afs/.:mount/{{ openafs_cell }}:root.cell/.
    -acl system:anyuser read

#
# Replicate the root.cell volume
#
- name: Add a read-only site for root.cell
  command: "{{ vos }} addsite -server {{ root_server }} -part {{ root_part }} -id root.cell"
  register: vos_result
  changed_when: vos_result.rc == 0
  failed_when: >
    vos_result.rc != 0
    and 'RO already exists on partition' not in vos_result.get('stderr','')

- name: Release root.cell
  command: "{{ vos }} release root.cell -verbose"

- name: Create root.cell read-write mount point
  command: >
    {{ fs }} mkmount
    -dir /afs/.:mount/{{ openafs_cell }}:root.afs/.{{ openafs_cell }}
    -vol root.cell
    -cell {{ openafs_cell }}
    -rw
  register: fs_result
  changed_when: fs_result.rc == 0
  failed_when: >
    fs_result.rc != 0
    and 'File exists' not in fs_result.get('stderr','')

#
# Replicate the root.afs volume.
#
- name: Add a read-only site for root.afs
  command: "{{ vos }} addsite -server {{ root_server }} -part {{ root_part }} -id root.afs"
  register: vos_result
  changed_when: vos_result.rc == 0
  failed_when: >
    vos_result.rc != 0
    and 'RO already exists on partition' not in vos_result.get('stderr','')

- name: Release root.afs
  command: "{{ vos }} release root.afs -verbose"

- name: Flush the volume cache
  command: "{{ fs }} checkvolumes"
